# Generated by Django 5.2.4 on 2026-05-14 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='My Dream Home', max_length=255)),
                ('total_area_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_floors', models.IntegerField(default=1)),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('quality_level', models.CharField(choices=[('STANDARD', 'Standard'), ('LUXURY', 'Luxury')], default='STANDARD', max_length=50)),
                ('estimated_material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('breakdown_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
