# Generated by Django 6.0.5 on 2026-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0003_alter_estimationhistory_id_alter_materialprices_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materialprices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
