# Generated by Django 5.2.4 on 2026-09-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0007_alter_estimationhistory_id_alter_materialprices_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materialprices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
