# Generated by Django 5.2.4 on 2026-09-09 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('worker_type', models.CharField(choices=[('PAINTER', 'Painter'), ('PLUMBER', 'Plumber'), ('ELECTRICIAN', 'Electrician'), ('GENERAL', 'General Worker'), ('WELDER', 'Welder'), ('MASON', 'Mason / Bricklayer'), ('CARPENTER', 'Carpenter'), ('TILER', 'Tiler'), ('DRIVER', 'Driver / Delivery'), ('HELPER', 'Site Helper / Labour')], max_length=30)),
                ('workers_needed', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('EXPIRED', 'Expired')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_daily_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='workers.dailyjob')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'worker')},
            },
        ),
    ]
