# Generated by Django 5.2.4 on 2026-09-09 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_alter_bid_id_alter_projectpost_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpost',
            name='ticket_required',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TicketBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocks_total', models.PositiveIntegerField(default=3)),
                ('unlocks_used', models.PositiveIntegerField(default=0)),
                ('price_paid', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXHAUSTED', 'Exhausted'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bundles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='bidding.projectpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_unlocks', to=settings.AUTH_USER_MODEL)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='bidding.ticketbundle')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
