# Generated by Django 5.2.4 on 2026-09-14 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0008_projectchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbundle',
            name='ticket_type',
            field=models.CharField(choices=[('BIDDING', 'Bidding Ticket'), ('QS', 'QS Consultation Ticket')], default='BIDDING', max_length=20),
        ),
        migrations.CreateModel(
            name='QSConnectionUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qs_unlocks', to='bidding.ticketbundle')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_unlocks', to=settings.AUTH_USER_MODEL)),
                ('qs_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_qs_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'qs_professional')},
            },
        ),
    ]
