# Generated by Django 5.2.4 on 2026-09-14 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0009_ticketbundle_ticket_type_qsconnectionunlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QSChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qs_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('unlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='bidding.qsconnectionunlock')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
