# Generated by Django 5.2.4 on 2026-05-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='material',
            name='ai_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price fetched by AI automatically', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='last_ai_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admins can set this if AI fails or price needs override', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='use_manual_price',
            field=models.BooleanField(default=False, help_text='If checked, the manual price is used instead of AI price'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.supplier'),
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='materials/images/')),
                ('is_main', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.material')),
            ],
        ),
    ]
