# Generated by Django 5.2.4 on 2026-05-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_material_unit_price_material_ai_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='brands', to='marketplace.materialcategory')),
            ],
        ),
    ]
