# Generated by Django 6.0.5 on 2026-05-14 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Homeowner'), ('PROFESSIONAL', 'Professional/Worker'), ('ADMIN', 'System Administrator')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_type', models.CharField(choices=[('CONTRACTOR', 'Contractor'), ('ENGINEER', 'Engineer'), ('LAWYER', 'Lawyer'), ('ARCHITECT', 'Architect'), ('QS', 'Quantity Surveyor (QS)'), ('HARDWARE', 'Hardware Owner'), ('WORKER', 'General Worker'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('WELDER', 'Welder'), ('PAINTER', 'Painter')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
                ('skills_specialization', models.CharField(blank=True, max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('projects_completed', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
