# Generated by Django 6.0.5 on 2026-05-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_id_alter_professionalprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='availability',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='pricing_range',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='service_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='years_in_business',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HardwareOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('shop_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('shop_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_registration', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('banner_image', models.FileField(blank=True, null=True, upload_to='hardware/banners/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_profile', to='users.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='hardware/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hardware_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='users.hardwareownerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalCertificationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='professional/certifications/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_images', to='users.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalPortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='professional/portfolio/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='users.professionalprofile')),
            ],
        ),
    ]
