# Generated by Django 6.0.5 on 2026-05-22 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_professionalprofile_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('shop_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('shop_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_registration', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('banner_image', models.FileField(blank=True, null=True, upload_to='hardware/shops/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_shops', to='users.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='hardware/shops/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='users.hardwareshop')),
            ],
        ),
    ]
