# Generated by Django 6.0.5 on 2026-05-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('users', '0006_hardwareshop_hardwareshopimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_shop_items', to='marketplace.material')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.hardwareshop')),
            ],
            options={
                'unique_together': {('shop', 'material')},
            },
        ),
    ]
