# Generated by Django 5.2.4 on 2026-09-13 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_id_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='badge_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='registration_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='registration_fee_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='service_fee_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='service_fee_plan',
            field=models.CharField(choices=[('NONE', 'None'), ('MONTHLY', 'Monthly Service Fee (LKR 500/mo)'), ('YEARLY', 'Yearly Service Fee (LKR 5,000/yr)'), ('PRO_MONTHLY', 'Pro Plan Monthly (LKR 550/mo)'), ('PRO_YEARLY', 'Pro Plan Yearly (LKR 5,000/yr)')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='service_fee_status',
            field=models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='INACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hardwaregalleryimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hardwareownerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hardwareshop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hardwareshopimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hardwareshopitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professionalcertificationimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professionalportfolioimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REGISTRATION_FEE', 'Professional Registration Fee (LKR 1,000)'), ('SERVICE_FEE_MONTHLY', 'Monthly Service Fee (LKR 500)'), ('SERVICE_FEE_YEARLY', 'Yearly Service Fee (LKR 5,000)'), ('VERIFIED_BADGE_YEARLY', 'Verified Badge Annual (LKR 1,000)'), ('PRO_PLAN_MONTHLY', 'Pro Plan Monthly (LKR 550)'), ('PRO_PLAN_YEARLY', 'Pro Plan Yearly (LKR 5,000)'), ('BIDDING_TICKET', 'Client Bidding Ticket (LKR 1,500)')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='MOCK_PAYMENT', max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
