# Generated by Django 5.2.4 on 2026-09-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_professionalprofile_badge_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REGISTRATION_FEE', 'Professional Registration Fee (LKR 1,000)'), ('SERVICE_FEE_MONTHLY', 'Monthly Service Fee (LKR 500)'), ('SERVICE_FEE_YEARLY', 'Yearly Service Fee (LKR 5,000)'), ('VERIFIED_BADGE_YEARLY', 'Verified Badge Annual (LKR 1,000)'), ('PRO_PLAN_MONTHLY', 'Pro Plan Monthly (LKR 550)'), ('PRO_PLAN_YEARLY', 'Pro Plan Yearly (LKR 5,000)'), ('BIDDING_TICKET', 'Client Bidding Ticket (LKR 1,500)'), ('QS_TICKET', 'Client QS Consultation Ticket (LKR 2,500)'), ('TICKET_PRO_PLAN', 'Client Ticket Pro Plan')], max_length=50),
        ),
    ]
